// action types for burgerBuilder REDUX State
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SAVE_INGR_STATE_ON_REFRESH = "SAVE_INGR_STATE_ON_REFRESH";
export const RELOAD_INGR_INITIAL_STATE = "RELOAD_INGR_INITIAL_STATE";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const ERROR_LOADING_INGREDIENTS = "ERROR_LOADING_INGREDIENTS";

// Action Types for Order REDUX State
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const INIT_PURCHASE = "INIT_PURCHASE";

export const INIT_ORDERS_SUCCESS = "INIT_ORDERS_SUCCESS";
export const INIT_ORDERS_FAIL = "INIT_ORDERS_FAIL";
export const INIT_ORDERS_START = "INIT_ORDERS_START";
