export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const UPDATE_STATE_ON_REFRESH = "UPDATE_STATE_ON_REFRESH";
export const RELOAD_INITIAL_STAGE = "RELOAD_INITIAL_STAGE";
